App\Entity\User:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3
          max: 250
          minMessage: El nombre tiene que tener al menos {{limit}} letras
          maxMessage: El nombre tiene que tener como maximo {{limit}} letras
          allowEmptyString: false
    email:
      - Email:
          message: El email "{{ value }}" no es valido.

App\Entity\WorkEntry:
  properties:
    userId:
      - NotBlank: ~
    startDate:
      - NotBlank: ~
